# Generated by Django 3.1.7 on 2021-04-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default=None, max_length=50, null=True)),
                ('region', models.CharField(default=None, max_length=5, null=True)),
            ],
        ),
    ]
