# Generated by Django 3.1.7 on 2021-04-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ramazon', '0002_auto_20210405_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
    ]
