# Generated by Django 3.1.7 on 2021-04-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ramazon', '0004_auto_20210406_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
    ]
