# Generated by Django 3.1.7 on 2021-04-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ramazon', '0005_remove_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='time',
            field=models.TimeField(),
        ),
    ]
