# Generated by Django 3.1.7 on 2021-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ramazon', '0008_auto_20210412_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='reg_asr',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_bamdod',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_peshin',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_shom',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_tong',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_xufton',
            field=models.TimeField(default=None, null=True),
        ),
    ]
