# Generated by Django 3.1.7 on 2021-04-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ramazon', '0009_auto_20210412_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note_time',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
