# Generated by Django 3.1.7 on 2021-04-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ramazon', '0010_user_note_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='note_time',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
