# Generated by Django 3.1.7 on 2021-04-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_ramazon', '0011_auto_20210412_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='note_babdod',
            new_name='note_bamdod',
        ),
    ]
